---
include:
  - board: levels54_left
  - board: levels54_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: crosses_left
  - board: nice_nano_v2
    shield: crosses_right